### Test 1: Delete Comment
POST {{baseUrl}}/Workplan/deleteComment
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "workplanExecutionId": 90011,
  "locationId": 88123,
  "commentId": 7781
}
