### Obtener unidades a monitorear
POST {{baseUrl}}/Unit/Monitoring
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "organizationId": 1,
  "divisionId": 3,
  "unitName": "CX"
}

### Sin token → 401
POST {{baseUrl}}/Unit/Monitoring
Content-Type: application/json

{
  "organizationId": 1,
  "divisionId": 3,
  "unitName": "CX"
}
