### Test 1: Get Report
POST {{baseUrl}}/Jobs/getReport
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "startDate": "2026-10-01T00:00:00",
  "endDate": "2026-10-07T23:59:59"
}

### Test 2: Get Report - By user
POST {{baseUrl}}/Jobs/getReport
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "startDate": "2026-10-01T00:00:00",
  "endDate": "2026-10-07T23:59:59",
  "userName": "jperez"
}
