### Test 1: Get Working Activity
POST {{baseUrl}}/Jobs/getWorkingActivity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "startDate": "2026-10-01T00:00:00",
  "endDate": "2026-10-07T23:59:59"
}
