### Eliminar cliente
DELETE {{baseUrl}}/Customer/Delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "customerId": "126"
}

### Sin token → 401
DELETE {{baseUrl}}/Customer/Delete
Content-Type: application/json

{
  "customerId": "126"
}
