### Desasignar una referencia a un cliente
POST {{baseUrl}}/Customer/UnassignLocation
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "customerId": 127,
  "locationId": 4157
}

### Sin token → 401
POST {{baseUrl}}/Customer/UnassignLocation
Content-Type: application/json

{
  "customerId": 127,
  "locationId": 4157
}
