### Obtener catálogo de rutas, con base en private codes del cliente y la referencia
POST {{baseUrl}}/Route/GetCatalog
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sourceCustomerPrivateCode": "GTC",
  "targetCustomerPrivateCode": "627511",
  "targetPrivateCode": "627511-1"
}
